### ISSUE TITLE
[BUG] Doing /chat results in error

### ISSUE THREAD

**Issue by larssieboy18** [yummypasta/AutoTeamChat#1]
Hi,

Thanks again for creating the plugin this quickly :) We have found a bug however. When someone does `/chat`, it gives this error: ```[16:16:54 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'chat' in plugin AutoTeamChat v1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Purpur-710]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.1.jar:git-Purpur-710]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Purpur-710]
        at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1976) ~[patched_1.16.1.jar:git-Purpur-710]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1779) ~[patched_1.16.1.jar:git-Purpur-710]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Purpur-710]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Purpur-710]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.1.jar:git-Purpur-710]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Purpur-710]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Purpur-710]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Purpur-710]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Purpur-710]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1205) ~[patched_1.16.1.jar:git-Purpur-710]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1198) ~[patched_1.16.1.jar:git-Purpur-710]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Purpur-710]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1174) ~[patched_1.16.1.jar:git-Purpur-710]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1018) ~[patched_1.16.1.jar:git-Purpur-710]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.1.jar:git-Purpur-710]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at com.yoonicode.autoteamchat.PluginCommands.onCommand(PluginCommands.java:56) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Purpur-710]
        ... 18 more
[16:17:04 INFO]: larssieboy18 issued server command: /chat all
[16:17:06 INFO]: larssieboy18 issued server command: /chat team```

It would be great if /chat would toggle between global and team chat, instead of resulting in this error :D

**Comment by ericyoondotcom** [comment]
Oops! I didn't think to implement a "toggle" feature when just `/chat` was typed. The plugin was supposed to give a nice error message in that case, but due to a typo it instead does this. I'll fix it and implement this!

**Comment by ericyoondotcom** [comment]
Fixed in [release 1.0.1](https://github.com/yummypasta/AutoTeamChat/releases/tag/v1.0.1)!
